### PR TITLE
Upgrade to Ember 2.8 for LTS

### PR DESCRIPTION
**Pull request by rox163**
#MAJOR#

# CHANGELOG
Upgrade Ember to v2.8 for LTS. 
Fixed tests and linting after upgrade.

### CODE REVIEW

**Comment by rox163** [comment]
- [ ] Add sass-lint
- [ ] Add md lint

**Comment by sglanzer** [comment]
Approved

**Comment by dafortin** [comment]
Build is failing because you are missing configurations in travis.yml. 

https://github.com/ciena-frost/ember-frost-info-bar/blob/master/.travis.yml#L1-L2
https://github.com/ciena-frost/ember-frost-info-bar/blob/master/.travis.yml#L35-L42

**Comment by rox163** [comment]
Yep working on it along with the lint tasks 👍

**Pull request merged**
