### PR TITLE
New Design

### PR DESCRIPTION
**Pull request by srowhani**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [x] #major# - incompatible API change

### Status
Ready for review

### Demo
http://srowhani.github.io/ember-frost-popover

It was brought to attention that absolute positioning seems to break where the popover is rendered. An alternative library that was found is `drop.js` which uses tether (handles a lot of these edge cases really well).

The way it behaves seems more consistent.

This is a WIP, let me know what you think, or any changes that come to mind.

# CHANGELOG
- Use tether.js to handle positioning

### CODE REVIEW

**Comment by sandersky** [comment]
I'm not sure I like the idea of using a library that hasn't been touched in over a year with 10 open PR's (which have been hanging around for a while) and 39 issues filed against it. https://github.com/HubSpot/drop I think we are probably better off improving our existing code to handle whatever edge cases it isn't covering, which I'm not even familiar with. To date I've been using this addon in an app and haven't had any issues whatsoever.

@sophypal @sglanzer thoughts?

**Comment by sglanzer** [comment]
@sandersky the latest implementation is based on `ember-tether` and we should be able to keep this from being a #major#

@srowhani explored a number of options to address positioning on-demand and this cuts the code base down significantly while improving the behaviour.

We'll give a good chance to review the final pass prior to merge

**Comment by sandersky** [comment]
Thanks @sglanzer, @srowhani when you think this PR is merge ready can you ping me so I can integration test it and make sure I see no regressions in my app.

**Comment by sglanzer** [comment]
That would be great, always nice to get confirmation from an actual app

**Comment by srowhani** [comment]
@sandersky Sounds good 👍

**Comment by sglanzer** [comment]
I know this has been open for a while, but any reason it was closed?

**Comment by srowhani** [comment]
I've been looking at popper.js or tippy as an alternative. They seem overall better than tether. (file size, responsiveness, es6)

**Comment by sglanzer** [comment]
Ok, I"ll re-close and let you pursue the other options

**Pull request closed without merging**
