### PR TITLE
onDisplay and onHide now pass the current object as a parameter

### LINKED ISSUE #44: When using ember-frost-list and selected list items a and b, where a has the popover it appears underneath item b
While using ember-frost-list, there is a bug where if in the list 2 adjacent items are checked for selected, that if item a has a this popover it will appear underneath item b. In this case when selected there's an outline and both of their z-indexes are set to 1. So the change for onDisplay and onHide was to allow a function to be passed in to do some post activity operations. In this particular case I am applying a larger z-index to the top level list item so it will overlay over item. I plan on making an internal component to wrap this one which will need the context of this component for my wrapper.

### PR DESCRIPTION
**Pull request by helrac**
I want to resolve #44 by passing in the current object so the component I am creating which extends this one. This descendant component will provide an onDisplay and onHide by default and requires the context of this component. So, I will pass 'this' as an argument so my onDisplay and onHide functions will have the context. 

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* **Modified** onDisplay and onHide now pass the current object as a parameter

### CODE REVIEW

**Comment by notmessenger** [comment]
What issue is this solving?  Why would the component need to be exposed like this?  How is it useful in a context outside of itself, rather than just passing relevant data needed?  Which goes back to my first question - what issue is this solving?

As an aside, we should not be opening PRs that do not have associated issues explaining the reason for them.  In absence of such issues (which we can work towards) the PR should at least contain this information.  There are two aspects to performing a PR: 1) checking that the solution solves the reason it is needed and 2) the quality and architecture of the code.  Without a reason for its existence Number 1 cannot be addressed and Number 1's reason influences Number 2.

**Comment by notmessenger** [comment]
@dafortin Why do we want to pass the entire component's content this way?  We should only pass what is needed.  I'm not even sure that this entire approach is necessary, regardless of the information that needs to be passed, but I haven't had a chance to evaluate this yet.

**Comment by notmessenger** [comment]
@dafortin 
>This descendant component will provide an onDisplay and onHide by default and requires the context of this component. So, I will pass 'this' as an argument so my onDisplay and onHide functions will have the context.

This is the whole point of the DDAU pattern and closure actions.   The approach taken should not be needed.

**Comment by sophypal** [comment]
I agree that passing in the `this` context is the wrong approach. If I understand the problem correctly, you want to be able to discern which item in a list the action belongs to right? If that's the case, I would use an action helper to wrap your action for `onDisplay` and provide context there, like maybe the list item index?

**Pull request merged**
